# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Article.create!(title: 'Article 1', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')
Article.create!(title: 'Article 2', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')
Article.create!(title: 'Article 3', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')
Article.create!(title: 'Article 4', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')
Article.create!(title: 'Article 5', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')
Article.create!(title: 'Article 6', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')
Article.create!(title: 'Article 7', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')
Article.create!(title: 'Article 8', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')
Article.create!(title: 'Article 9', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')
Article.create!(title: 'Article 10', description: "Vogue Daily. The latest in top fashion stories, editor's picks, and celebrity style. ... The latest fashion news, beauty coverage, celebrity style, fashion week ... ", url: 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.canva.com%2Ftemplates%2Fs%2Farticle%2F&psig=AOvVaw2wi-_Z5hllUDEvMl5moV-t&ust=1716101339694000&source=images&cd=vfe&opi=89978449&ved=0CBUQ3YkBahcKEwiQgJj9zZaGAxUAAAAAHQAAAAAQCQ', image: 'https://marketplace.canva.com/EAFj2v65I38/2/0/1131w/canva-brown-modern-fashion-magazine-article-a4-document-251z_8TyZVg.jpg')


